// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCEo8JvmCnFTUTILILFFE82aKzXEQSpEI',
    appId: '1:38382889122:web:a92e36d0853a0afa2c0ffb',
    messagingSenderId: '38382889122',
    projectId: 'book-app-a3009',
    authDomain: 'book-app-a3009.firebaseapp.com',
    storageBucket: 'book-app-a3009.firebasestorage.app',
    measurementId: 'G-KXWTTV8BPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNrho_F6nQ4PxAPLIxDqLAAI9FBLsMjEQ',
    appId: '1:38382889122:android:b162bac24f02da302c0ffb',
    messagingSenderId: '38382889122',
    projectId: 'book-app-a3009',
    storageBucket: 'book-app-a3009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnwkqK23BzQzoTSiTf9iI3hSvHjjfwa9E',
    appId: '1:38382889122:ios:678dce36742a148a2c0ffb',
    messagingSenderId: '38382889122',
    projectId: 'book-app-a3009',
    storageBucket: 'book-app-a3009.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );
}
